@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle and Equipment\nFleet Manager" as ADM
participant ":ListVehiclesCheckupUI" as UI
participant ":ListVehiclesCheckupController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehiclesRepository\n:VehiclesRepository" as VehRepo
participant "Vehicle" as Veh

activate ADM
    ADM -> UI : asks to list the vehicles needing a check-up

    activate UI
        UI -> CTRL** : create
        UI -> CTRL : getVehiclesNeedingCheckup()

        activate CTRL

            CTRL -> RepositorySingleton : getInstance()

            activate RepositorySingleton
                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getVehiclesRepository()

            activate PLAT
                PLAT --> CTRL: vehiclesRepository
            deactivate PLAT

            CTRL -> VehRepo : getVehicles()

            activate VehRepo
                VehRepo --> CTRL : vehicles
            deactivate VehRepo

            loop as long as VehiclesRepository doesn't end.

                CTRL -> Veh : isVehicleNeedingOrAlmostCheckup()

                activate Veh

                    Veh -> Veh : didVehExceededCheckup()
                    activate Veh
                        Veh --> Veh : true/false
                    deactivate Veh

                    Veh -> Veh : isVehicleCloseToExceedCheckup()

                    activate Veh
                        Veh --> Veh : true/false
                    deactivate Veh

                    alt didVehExceededCheckup() == true
                        Veh --> CTRL : true
                    else isVehicleCloseToExceedCheckup() == true
                        Veh --> CTRL : true
                    else
                        Veh --> CTRL : false
                    end

                deactivate Veh

            end

            CTRL --> UI : vehiclesNeedingCheckup
        deactivate CTRL

        UI --> ADM : Shows the list of vehicles needing or almost needing check-up.
    deactivate UI

deactivate ADM

@enduml