@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Vehicle and Equipment \nFleet Manager" as VFM
participant "System" as System

activate VFM

    VFM -> System : asks to register a new vehicle
    activate System

    loop while intended
            System --> VFM : requests vehicle data (i.e. Brand, Model, Type, Tare,Gross Weight, \nCurrent Km, Register Date, Acquisition Date,\n Maintenance/Checkup Frequency (in Kms), vehicle plate)
        deactivate System

        VFM -> System : write the values of the new vehicle's attributes
        activate System
    end

        System --> VFM : shows all registered vehicles and asks to confirm the data of the new vehicle typed in
    deactivate System

    VFM -> System : confirms the set of registered vehicles and the new vehicle
    activate System

    System --> VFM : displays operation success
    deactivate System
@enduml