@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Vehicle and Equipment \nFleet Manager" as VFM
participant "System" as System

activate VFM

    VFM -> System : asks to register a new vehicle
    activate System

        System --> VFM : requests vehicle data (i.e. Brand, Model, Type, Tare,Gross Weight, \nCurrent Km, Register Date, Acquisition Date,\n Maintenance/Checkup Frequency (in Kms), vehicle plate)
    deactivate System

    VFM -> System : fills in the fields with the required attributes
    activate System

    alt some invalid vehicle attribute
        loop as long as the attribute stills invalid
               VFM -> System : writes the value of the attribute again
                    activate System

                        System --> VFM : validates the vehicle attribute
                    deactivate System
        end
    else all valid vehicle attributes
        VFM -> System : confirms the registration of a new vehicle
            activate System

        System --> VFM : show an alert saying that the vehicle has been successfully registered
            deactivate System
    end

@enduml