@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class Job {
    - String jobName
    + registJob()
}

class RegistedJobsRepository {
    + getRegistJob()
}

class Repositories {
    - repositories()
    + getInstance() : Repositories
    + getRegistedJobsRepository()
}

class RegistJobController {
    + registJobController()
    + getRegistJob()
    + registJob(jobName)
}

class RegistJobUI {
}

RegistJobUI .> RegistJobController

RegistJobController .> Repositories : repositories

Repositories -> "1" RegistedJobsRepository

RegistJobController ..> Job
RegistJobController ..> RegistedJobsRepository : RegistedJobsRepository


RegistedJobsRepository "1" --> "*" Job : RegistJob


@enduml