@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "registedJobsRepository:\nRegistedJobsRepository" as RegistedJobsRepository
participant "name\n:Job" as PROFISSAO

autonumber 10
-> RegistedJobsRepository: create
activate RegistedJobsRepository

    group Create a Job

        RegistedJobsRepository -> PROFISSAO**: create
        RegistedJobsRepository -> RegistedJobsRepository: addJob(name)

            RegistedJobsRepository -> RegistedJobsRepository: validateJob(name)

    end

    <-- RegistedJobsRepository : registedJobsList

deactivate RegistedJobsRepository


@enduml