@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Human Resources\nManager" as HRM
participant ":RegistJobUI" as UI
participant ":RegistJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "registedJobsRepository:\nRegistedJobsRepository" as RegistedJobsRepository
participant "jobName\n:Job" as PROFISSAO

autonumber 1

activate HRM

    HRM -> UI : asks to regist a new job
    activate UI

        UI -> CTRL** : create

        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getRegistedJobsRepository()
        activate PLAT

            PLAT --> CTRL: registedJobsRepository
        deactivate PLAT

        deactivate CTRL

    loop while intended
            UI --> HRM : requests the job name
        deactivate UI

        HRM -> UI : type the new job
        activate UI
            UI -> CTRL: create
        activate CTRL

            CTRL -> RegistedJobsRepository : create

            activate RegistedJobsRepository

                RegistedJobsRepository -> PROFISSAO**: create
                PROFISSAO -> RegistedJobsRepository: addJob(jobName)

                    RegistedJobsRepository -> RegistedJobsRepository: validateJob(jobName)

    end
                RegistedJobsRepository --> CTRL : registedJobsList
            deactivate RegistedJobsRepository

            CTRL --> UI : registedJobsList
        deactivate CTRL

        UI --> HRM : list all registered jobs and asks to confirm

            deactivate CTRL
        deactivate UI

    HRM -> UI : confirms all jobs
    activate UI

    UI --> HRM : displays operation success
    deactivate UI

@enduml