@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Human Resources\nManager" as HRM
participant ":RegistJobUI" as UI
participant ":RegistJobController" as CTRL
participant "registedJobsRepository:\nRegistedJobsRepository" as RegistedJobsRepository

autonumber 1

activate HRM
    HRM -> UI : asks to regist a new job
    activate UI
        UI -> CTRL** : create
        activate CTRL
        ref over CTRL
            Get Registed Jobs Repository
        end ref

    loop while intended
            autonumber 7
            UI --> HRM : requests the job name
        deactivate UI
        HRM -> UI : type the new job
        activate UI
            UI --> CTRL: create
        activate CTRL
            CTRL --> RegistedJobsRepository : create
            activate RegistedJobsRepository
            autonumber 14
            ref over RegistedJobsRepository
                Get Registed Jobs List
            end ref
    end
                RegistedJobsRepository --> CTRL : registedJobsList
            deactivate RegistedJobsRepository
            CTRL --> UI : registedJobsList
        deactivate CTRL
        UI --> HRM : list all registered jobs and asks to confirm
            deactivate CTRL
        deactivate UI
    HRM -> UI : confirms all jobs
    activate UI
    UI --> HRM : displays operation success
    deactivate UI

@enduml