@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "registedJobsRepository:\nRegistedJobsRepository" as RegistedJobsRepository
participant "jobName\n:Job" as PROFISSAO

autonumber 10
-> RegistedJobsRepository: create
activate RegistedJobsRepository

    group Create a Job

        RegistedJobsRepository -> PROFISSAO**: create
        RegistedJobsRepository -> RegistedJobsRepository: addJob(jobName)

            RegistedJobsRepository -> RegistedJobsRepository: validateJob(jobName)

    end

    <-- RegistedJobsRepository : registedJobsList

deactivate RegistedJobsRepository


@enduml