@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to assign one or more skills to a collaborator
    activate System

        System --> Employee : requests the collaborator to assign skills to
    deactivate System

    Employee -> System : types the collaborator information
    activate System

        System --> Employee : requests skill(s)
    deactivate System

    Employee -> System : type the skill(s)
    activate System

        System --> Employee : shows all the skill(s), the collaborator and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml