@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Vehicle Fleet\nManager" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "VehiclesRepository:\nVehiclesRepository" as VehiclesRepository
participant "PlateCertificationsRepository:\nPlateCertificationsRepository" as PlateCertificationsRepository
participant "vehicle\n:Vehicle" as VEICULO
participant "plateCertification\n:PlateCertification" as PLATE_CERTIFICATION

autonumber 1

activate VFM

VFM -> UI : asks to register a new vehicle
activate UI

UI -> CTRL : create
activate CTRL

ref over CTRL
    Get Vehicles Repository
end ref
deactivate CTRL

loop while intended
autonumber 9
UI --> VFM : requests vehicle data (i.e. Brand, Model, Type, \nTare,Gross Weight, Current Km, Register Date, \nAcquisition Date, Maintenance/Checkup Frequency (in Kms),\n vehicle plate)

deactivate UI

VFM -> UI : write the values of the new vehicle's attributes
activate UI

UI -> CTRL: create
activate CTRL

CTRL -> VehiclesRepository : create
activate VehiclesRepository

ref over VehiclesRepository,PlateCertificationsRepository
    Get Vehicles List
end ref

deactivate VehiclesRepository
deactivate CTRL
end

activate PlateCertificationsRepository
autonumber 31
CTRL <-- PlateCertificationsRepository : plateCertificationsList
deactivate PlateCertificationsRepository

CTRL --> UI : plateCertificationsList
activate VehiclesRepository
CTRL <-- VehiclesRepository : vehiclesList
CTRL --> UI : vehiclesList
deactivate VehiclesRepository
deactivate CTRL

UI --> VFM : shows all registered vehicles and asks to confirm
deactivate UI

VFM -> UI : confirms all vehicles
activate UI
UI --> VFM : displays operation success
deactivate UI

@enduml
