@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resources \n Manager" as HRM
participant "System" as System

activate HRM

    HRM -> System : asks to regist a new job
    activate System

    loop while intended
            System --> HRM : requests the job name (i.e.  designer, budgetist,\n gardener, electrician or bricklayer...)
        deactivate System

        HRM -> System : type the new job
        activate System
    end

        System --> HRM : list all registered jobs and asks to confirm the new typed job
    deactivate System

    HRM -> System : confirms the set of registered jobs and the new typed job
    activate System

    System --> HRM : displays operation success
    deactivate System

@enduml