@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

skinparam classAttributeIconSize 0


class GenerateTeamProposalUI {
}

class GenerateTeamProposalController {
    + GenerateTeamProposalController(SkillsRepository, CollaboratorsRepository, TeamRepository)
    + getSkillsList()
    + getCollaboratorsList()
    + getCollaboratorSkillsList()
    - getTeam()
}

class Collaborator {
    - String name
    - Date bornDate
    - Date admDate
    - int phoneNumber
    - String email
    - int idCard
    - int idNumber

    + Collaborator(name, bornDate, admDate, phoneNumber, email, idCard, idNumber)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getSkillsRepository()
    + getCollaboratorsRepository()
    + getTeamRepository()
}

class CollaboratorsRepository {
    + getCollaboratorsList()
}

class CollaboratorSkills {
    + getCollaboratorSkillsList()
}

class SkillsRepository {
    + getSkillsList()
}

class SkillsSelected {
    + getSkillsSelected()
}

class Address {
    - int doorNumber
}

class ZipCode {
    - int local
    - int street
}

class TeamRepository {
    + getTeam()
}

class Team {
    - String name
    + addCollaborator(collaborator)
    + Team(name)
}


Repositories -> Repositories : instance

GenerateTeamProposalUI .> GenerateTeamProposalController

Repositories --> "1" TeamRepository
Repositories --> "1" CollaboratorsRepository
Repositories --> "1" SkillsRepository

GenerateTeamProposalController ...> CollaboratorsRepository: CollaboratorsRepository
GenerateTeamProposalController ...> SkillsRepository: SkillsRepository
GenerateTeamProposalController ...> TeamRepository : TeamRepository
GenerateTeamProposalController .> Repositories : repositories
GenerateTeamProposalController ...> "1" Collaborator : Collaborator

TeamRepository --> "*" Team : teams
Team o-- "*" Collaborator : has

SkillsRepository --> "*" SkillsSelected

CollaboratorsRepository --> "*" Collaborator

Collaborator *-- "1" Address : owns
Address *-- "1" ZipCode : owns

Collaborator *-- "*" CollaboratorSkills


@enduml