@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "registedSkillsRepository\n:RegistedSkillsRepository" as RegistedSkillsRepository

autonumber 4
-> CTRL : getRegistedSkillsList()

activate CTRL

group Get Registed Skills List

    CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

    CTRL -> PLAT : getRegistedSkillsRepository()
activate PLAT

PLAT --> CTRL: registedSkillsRepository
deactivate PLAT

    CTRL -> RegistedSkillsRepository : getRegistedSkillsList()
activate RegistedSkillsRepository

RegistedSkillsRepository --> CTRL : registedSkillsList
deactivate RegistedSkillsRepository

<-- CTRL : registedSkillsList
deactivate CTRL

end

@enduml