@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods


class MusgoSublime {
    name
    vatNumber
    website
    phoneNumber
    email
}

class HumanResourceManager {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class Collaborator {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class FleetManager {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class Skill {
    skillName
}

class Job {
    jobName
}

class Team {
    membersName
    skillsName
}

class Vehicle {
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    maintenance
    plate
}

class VehicleCheckUp {
    Date
    Place
}
'
'class TechnicalSkill{
'    shortDescription
'    fullDescription
'}

'class ActivityArea{
'    shortDescription
'    fullDescription
'}

'class FeatureTS{
'    mandatory
'}

'class PostalAddress{
'    street
'    zipCode
'    city
'}


MusgoSublime "1" - "1..*" HumanResourceManager: has >
MusgoSublime "1" - "1..*" Collaborator: has >
MusgoSublime "1" - "1..*" FleetManager: has >
MusgoSublime "1" - "1..*" Skill: owns >
MusgoSublime "1" - "1..*" Job: owns >
MusgoSublime "1" - "1..*" Team: owns >
MusgoSublime "1" - "1..*" Vehicle: owns >
HumanResourceManager "1" -- "1..*" Skill : regist >
HumanResourceManager "1" -- "1..*" Job : regist >
HumanResourceManager "1" -- "1..*" Collaborator : regist >
HumanResourceManager "1" -- "1..*" Team : creates >
Collaborator "1..*" -- "1" Job : assigned to <
Collaborator "1..*" -- "*" Skill : assigned to <
Team "1" -- "1..*" Collaborator : has >
FleetManager "1" -- "1..*" Vehicle : regist >
FleetManager "1" -- "1..*" VehicleCheckUp : regist >
Vehicle "1" -- "*" VehicleCheckUp : assigned to <



'TechnicalSkill "*" - "1" ActivityArea: regarding an >
'HumanResourceManager "*" - "*" TechnicalSkill :  : requires >
'(HumanResourceManager, TechnicalSkill) . FeatureTS
'MusgoSublime "1" -left "1" PostalAddress : located At >

@enduml