@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class Organization {
}

class HumanResourceManager {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class Skill {
    skillName
}


Organization "1" - "1..*" HumanResourceManager: has >
Organization "1" - "1..*" Skill: owns >
HumanResourceManager "1" -- "1..*" Skill : regist >

@enduml