@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class HRM {
    name
    email
    position
    phone
}

class Skills {
    name
}


Organization "1" - "1" HRM: has >
HRM "1" -- "0..*" Skills : regist >

@enduml