@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class MusgoSublime {
    name
    vatNumber
    website
    phoneNumber
    email
}

class HumanResourceManager {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class Skill {
    skillName
}


MusgoSublime "1" - "1..*" HumanResourceManager: has >
MusgoSublime "1" - "1..*" Skill: owns >
HumanResourceManager "1" -- "1..*" Skill : regist >

@enduml