@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class HRM {
    name
    email
    position
    phone
}

class Skills {
    name
}

class Collaborator {
    name
    email
    position
    phone
}

class GenerateTeam {
    membersName
    skillNames
}

Organization "1" - "0..*" Skills: owns >
Organization "1" - "0..*" Collaborator: owns >
Organization "1" - "1" HRM : has >
Organization "1" - "0..*" GenerateTeam: owns >
HRM "1" -- "*" GenerateTeam : creates >
@enduml