@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class MusgoSublime {
}

class HumanResourceManager {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class Skill {
    skillName
}

class Collaborator {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class Team {
}

MusgoSublime "1" - "1..*" Collaborator: has >
MusgoSublime "1" - "1..*" HumanResourceManager : has >
Collaborator "*" -- "*" Skill : owns >
MusgoSublime "1" - "1..*" Team: owns >
Team "1" -- "1..*" Collaborator : has >
HumanResourceManager "1" -- "1..*" Team : creates >
@enduml