@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to regist a new collaborator
    activate System

    loop while intended
            System --> HRM : requests the job
        deactivate System
        HRM -> System : Type a job
        activate System

        System --> HRM : requests the fundamental characteristics (i.e. name, birth date, admission date,\n address, contact info (mobile and email), taxpayer number,ID doc type and respective number)
        deactivate System
        HRM -> System : Type the fundamental characteristics
        activate System
        System --> HRM : Request confirmation
        deactivate System
        HRM -> System : Confirms it and regist the new collaborator
        activate System
    end

        System --> HRM : show all the collaborators registed
    deactivate System

    HRM -> System : confirm the collaborator(s) registed and requests confirmation
    activate System

    System --> HRM : displays operation success
    deactivate System


@enduml