@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "skillsRepository:\nSkillsRepository" as SkillsRepository
participant "skillName\n:Skill" as TAREFA

autonumber 10
-> SkillsRepository: create

activate SkillsRepository
    group Create Skill

        SkillsRepository -> TAREFA**: create
                activate TAREFA

                TAREFA -> TAREFA: validateSkill(skillName)

                TAREFA --> SkillsRepository : skillName
                SkillsRepository -> SkillsRepository: validateSkill(skillName)
                deactivate TAREFA
                SkillsRepository -> SkillsRepository: addSkill(skillName)
                SkillsRepository -> SkillsRepository: true/false
                SkillsRepository -> SkillsRepository: true/false

    end

    <-- SkillsRepository : registedSkillsList

deactivate SkillsRepository


@enduml