@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Human Resources\nManager" as HRM
participant ":RegistSkillsToCollaboratorsUI" as RGC

autonumber 1

activate HRM

    HRM -> RGC : asks to regist a new skill
    activate RGC

    RGC ->: getRegistSkillsToCollaborators()

    loop while intended
            RGC --> HRM : requests the skill name
        deactivate RGC

        HRM -> RGC : types the new skill name
        activate RGC
    end

        RGC --> RGC: keepData

        RGC --> HRM : show all the skills registed and aks to confirm
    deactivate RGC

    HRM -> RGC : confirm the set of skills registed
    activate RGC

    RGC -->: RegistSkillsToCollaborators

    RGC --> HRM : displays operation success
    deactivate RGC


@enduml