@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class Skill {
    - String skillName
    + Skill()
}

class SkillsRepository {
    + getSkill()
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getSkillsRepository()
}

class RegisterSkillController {
    + RegisterSkillController()
    + getSkill()
    + Skill(skillName)
}

class RegisterSkillUI {
}

RegisterSkillUI .> RegisterSkillController

RegisterSkillController .> Repositories : repositories

Repositories -> "1" SkillsRepository

RegisterSkillController ..> Skill
RegisterSkillController ..> SkillsRepository : SkillsRepository


ApplicationSession --> "1" UserSession : userSession

RegisterSkillController ..> ApplicationSession
RegisterSkillController ..> UserSession
SkillsRepository "1" --> "*" Skill : Skill


@enduml