@startuml
/'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Human Resources\nManager" as HRM
participant ":RegistSkillsToCollaboratorsUI" as UI

autonumber 1

activate HRM

    HRM -> UI : asks to regist a new skill
    activate UI

    UI ->: getRegistSkillsToCollaborators()

    loop while intended
            UI --> HRM : requests the skill name
        deactivate UI

        HRM -> UI : types the new skill name
        activate UI
    end

        UI --> UI: keepData

        UI --> HRM : show all the skills registed and aks to confirm
    deactivate UI

    HRM -> UI : confirm the set of skills registed
    activate UI

    UI -->: RegistSkillsToCollaborators

    UI --> HRM : displays operation success
    deactivate UI

'/

@enduml
*/
