@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":RegistSkillsToCollaboratorsUI" as UI
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "registedSkillsRepository:\nRegistedSkillsRepository" as RegistedSkillsRepository

autonumber 3

 -> UI : getRegistedSkills()
autonumber 3.1
activate UI
    group Get Registed Skills

            UI -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> UI: repositories
            deactivate RepositorySingleton

            UI -> PLAT : getRegistedSkillsRepository()
            activate PLAT

                PLAT --> UI: registedSkillsRepository
            deactivate PLAT

            UI -> RegistedSkillsRepository : getRegistedSkills()
            activate RegistedSkillsRepository

                RegistedSkillsRepository --> UI : registedSkillsList
            deactivate RegistedSkillsRepository


    end
    autonumber 4
    <-- UI  : registedSkillsList
deactivate UI


@enduml