@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "registedSkillsRepository:\nRegistedSkillsRepository" as RegistedSkillsRepository
participant "skill\n:Skill" as TAREFA

autonumber 11
-> RegistedSkillsRepository: createSkill

activate RegistedSkillsRepository
    group Create Skill

        RegistedSkillsRepository -> TAREFA**: create skill
        TAREFA -> RegistedSkillsRepository: addSkill (skill)

            RegistedSkillsRepository -> RegistedSkillsRepository: validateSkill(skill)

    end

    <-- RegistedSkillsRepository : registedSkillsList

deactivate RegistedSkillsRepository


@enduml