@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "registSkill\n:RegistSkill" as TAREFA

autonumber 1
-> ORG: Regist Skills to Collaborators

autonumber 1.1
activate ORG
    group Regist Skills to Collaborators

        ORG -> TAREFA**: type the name of the skill

        ORG -> ORG: addSkill(skill)

        ORG -> ORG: validateSkill(skill)

    end

    autonumber 2
    <-- ORG : registSkill
deactivate ORG


@enduml