@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class RegisterVehicleUI {
}

class RegisterVehicleController {
    + RegisterVehicleController()
    + getVehiclesList()
    + getPlateCertificationsList()
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehiclesRepository()
    + getPlateCertificationsRepository()
}

'----------------CLASSES PLATE CERTIFICATION-------------

class Vehicle {
    - double currentKm
    - Date acquisitionDate
    - double maintenance
    + Vehicle(vehicle)
    + validateVehicle(vehicle)
}

class VehiclesRepository {
    + getVehiclesList()
    + addVehicle(vehicle)
    + validateVehicle(vehicle)
}

RegisterVehicleUI .> RegisterVehicleController

RegisterVehicleController .> Repositories : repositories

'-----------LIGAÇÕES VEHICLE------

Repositories --> "1" VehiclesRepository

RegisterVehicleController ..> Vehicle : Vehicle
RegisterVehicleController ..> VehiclesRepository : VehiclesRepository

VehiclesRepository "1" --> "*" Vehicle

'----------------CLASSES PLATE CERTIFICATION-------------
class PlateCertification {
    - String brand
    - String model
    - String type
    - double tare
    - double grossWeight
    - Date registerDate
    - String plate
    + PlateCertification(plateCertification)
    + validatePlateCertification(plateCertification)
}

class PlateCertificationsRepository {
    + getPlateCertificationsList()
    + addPlateCertification(plateCertification)
    + validatePlateCertifications(plateCertification)
}

'-----------LIGAÇÕES PLATE CERTIFICATION------

Repositories --> "1" PlateCertificationsRepository

RegisterVehicleController ..> PlateCertification : PlateCertification
RegisterVehicleController ..> PlateCertificationsRepository : PlateCertificationsRepository

PlateCertificationsRepository "1" --> "*" PlateCertification

Vehicle *-- "1" PlateCertification : assigned to

@enduml