@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class MusgoSublime {
    name
    vatNumber
    website
    phoneNumber
    email
}

class FleetManager {
    name
    bornDate
    admDate
    address
    phoneNumber
    email
    idCard
    idNumber
}

class Vehicle {
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    maintenance
    plate
}

MusgoSublime "1" - "1..*" FleetManager: has >
FleetManager "1" -- "1..*" Vehicle : regist >
@enduml