@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Collaborator {
    -skills
    +assignSkills(skillsToAssign)
}

class SkillsRepository {
    - skillsRepository
    + getAllSkills()
}

class CollaboratorsRepository {
    - collaboratorsRepository
    + getAllCollaborators()
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getCollaboratorsRepository()
    + getSkillsRepository()
}

class AssignSkillController {
    - collaboratorSelected
    + setCollaboratorSelected(collaboratorSelected)
    + getCollaborators()
    + getSkills()
    + storeSkills(skillsToAssign)
}

class AssignSkillUI {
}

AssignSkillUI .. AssignSkillController

AssignSkillController .. Repositories

AssignSkillController .. CollaboratorsRepository

AssignSkillController .. SkillsRepository

AssignSkillController .. Collaborator

Repositories *- CollaboratorsRepository

Repositories *- SkillsRepository

CollaboratorsRepository o- Collaborator

@enduml