@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to regist a new skill
    activate System

    loop while intended
            System --> HRM : requests the skill (i.e. driving vehicles, operating machines,\n tree pruning, application of phytopharmaceuticals.)
        deactivate System

        HRM -> System : regist the new skill
        activate System
    end

        System --> HRM : show all the skills registed
    deactivate System

    HRM -> System : confirm the set of skills registed and aks to confirm
    activate System

    System --> HRM : displays operation success
    deactivate System


@enduml