@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to regist a new skill
    activate System

        System --> HRM : requests the skills (i.e. driving vehicles, operating machines,\n tree pruning, application of phytopharmaceuticals.)
    deactivate System

    HRM -> System : regist new(s) skill(s)
    activate System

        System --> HRM : show all the skills registed
    deactivate System

    HRM -> System : confirm skill(s) selected
    activate System

        System --> HRM : displays operation success
    deactivate System


@enduml