@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to type the maximum number of team collaborators
    activate System

        System --> HRM : requests which is the maximum number of team collaborators
    deactivate System

    HRM -> System : types the maximum number of team collaborators
    activate System

        System --> HRM : show the maximum number of team collaborators registed
    deactivate System

    HRM -> System : asks to type the skill needed
    activate System

    loop while intended
            System --> HRM : requests which are the skill needed\n(i.e. 4 tree pruner and 1 light vehicle driver)
        deactivate System

        HRM -> System : types the skill
        activate System
    end

        System --> HRM : show the skill typed
            deactivate System

    HRM -> System : asks to generate a team proposal
    activate System

        System --> HRM : shows the generated team proposal and aks to confirm the data
    deactivate System

    HRM -> System : confirms all the data (size of team, skills and team generated)
    activate System

        System --> HRM : displays operation success
    deactivate System


@enduml